version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_api_php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    working_dir: /var/www/html

  web:
    image: nginx:latest
    container_name: symfony_api_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony_api_db
    ports:
      - "5501:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

